name: Test Slack Notification

on:
  push:
    branches: ["test-slack"]

env:
  APP_ENV: ${{ secrets.PRODUCTION }}
  STATUS: "❌"

jobs:
  build:
    name: "Test Slack Notification"
    runs-on: ubuntu-latest

    steps:
      - name: Default Status
        run: echo "STATUS=✅" >> $GITHUB_ENV

      - name: Post build result to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: "C053HR3MDQB"
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ env.STATUS }} ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        if: always()
